# Conexión a la Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/valenci_db
spring.datasource.username=root
spring.datasource.password=123456

# Configuración de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Secreto para firmar el token JWT
jwt.secret=in8JX0b3Pda5twwDvap4bkvbeDIS5yIC3x/ZZWJHof4=

# Nivel de log general para toda la aplicación (ej. INFO)
logging.level.root=INFO

# Nivel de log específico para tu paquete de servicios (ej. DEBUG para ver más detalle)
logging.level.com.valenci.servicios=DEBUG

# Nivel de log para ver las consultas SQL de Hibernate (muy útil para depurar)
logging.level.org.hibernate.SQL=DEBUG

# Tasa de IVA para la aplicación (0.19 = 19%)
app.iva.tasa=0.19
